# This is a basic workflow to help you get started with Actions

name: "Changelog Generate"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "changelog"
  changelog:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checkout code
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Generate changelog
      - name: Generate changelog
        uses: heinrichreimer/action-github-changelog-generator@v2.2
        id: changelog_generate
        with:
          repo: "rohsyl/changeloggentest1"
          token: ${{ secrets.GITHUB_TOKEN }}
          configureSections: "{feature:{prefix:\"**New features:**\",labels:[\"feature\",\"Feature\"]},maintenance:{prefix:\"**Maintenance:**\",labels:[\"maintenance\"]},hotfix:{prefix:\"**Documentation updates:**\",labels:[\"hotfix\",\"bug\",\"Bug\"]},wontfix:{prefix:\"**Won't fix:**\",labels:[\"wontfix\"]}}"
          unreleased: false
          stripGeneratorNotice: true
          onlyLastTag: true
          verbose: true

      - name: Prepare changelog
        id: changelog_string
        run: |
          export CHANGELOG="${{ steps.changelog_generate.outputs.changelog }}"
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          echo "::set-output name=changelog::$CHANGELOG"

      - name: Send changelog to Microsoft Teams
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MSTEAMS_WEBHOOK }}
          title: "New release of CoucouApp"
          summary: "Generated changelog for new CoucouApp release"
          text: "${{ steps.changelog_string.outputs.changelog }}"
